### ISSUE TITLE
Database pk

### ISSUE THREAD

**Issue by mcardenass** [xtyangpsp/StackMaster#2]
How do I convert my sac files to .pk database?

**Comment by xtyangpsp** [comment]
Thanks for using stackmaster. Converting to .pk files is not required to use the stacking functions. As long as you can read your sacfiles as Obspy traces, you can gather all trace data (the time series vectors) into a 2-d matrix. Then you can call the stacking functions to operate on the 2-d matrix. Hope this helps.

**Comment by mcardenass** [comment]
Thanks Xiaotao
