### ISSUE TITLE
Strange strips on tf-pws result

### ISSUE THREAD

**Issue by RunningXinLiu** [xtyangpsp/StackMaster#3]
HI Prof. Yang,

Thanks for sharing those codes or stacking! However, I was unable to install the python packages possibly due to my mac m1 architecture. But the matlab codes work fine for me.

The only problem is when I applied the tf-pws code with my data, some weird strips appeared, which is not seen on linear stacking nor the pws stacking.
![tf-pws](https://github.com/xtyangpsp/StackMaster/assets/44730577/e2bf5730-2ef2-4b6f-8b2c-c489e2577725)
tf-pws stacking
![pws](https://github.com/xtyangpsp/StackMaster/assets/44730577/ab002855-2c14-4b3c-936d-f4334d3b0852)
pws stacking (same as linear stacking)

1. I have tested different water level selection for tf-pws but it doesn't fix the problem.
2. My raw 1 minute waveform data is windowed into several 10s segments, then CCFs of the 10s data are linearly stacked to get the CCF of that 1 minute data. After this, all CCFs of different 1 minute data are tf-pws stacked to get the final result. Therefore, my stacking is not a perfect tf-pws stacking but I don't think it will cause the strange strips on my final results. 

Best,
Xin

**Comment by xtyangpsp** [comment]
Hi Xin,

Thanks for using StackMaster. Sorry to hear the issues. We have not fully tested the MATLAB version tf-pws stacking code yet. The Stockwell transform with DOST in MATLAB might not be correct. Other stacking methods should be good to use in MATLAB. If you just need one stacking, as tested in the GJI paper (Yang et al., 2022), PWS might not be a good choice. The Robust stacking method has the best overall performance. 

BTW, what are the errors you got when installing the python version? I have installed the packed on both M1 and M2 (including M2 Pro) computers. 

Xiaotao

**Comment by RunningXinLiu** [comment]
The python installation error message is "conda-forge/osx-arm64 inconsistency". This might be caused by my previous mishandling of a python package which requires python 2.7, when I messed up my system setting. 
Since you have no problem with m1 and m2, I will try to reinstall your repo. Thanks for sharing your codes!

Best,
Xin

**Comment by RunningXinLiu** [comment]
I am working on a field DAS data and many literatures recommend tf-pws. I will definitely try other stacking methods you provided.

**Comment by xtyangpsp** [comment]
The installation error is likely due to package versions. We only tested on Python >=3.6. I don’t know why tf-pws is recommended. It might help if you could install the python version and compare the tf-pws results with other stacking results. tf-PWS is much slower than other methods, while not showing notable advantages in the stacking result. You can check out our paper for the comparisons with multiple metrics: https://academic.oup.com/gji/article/232/3/1600/6762921

**Comment by RunningXinLiu** [comment]
Yes, it might be the version problem. Previously I forced my python version to be 2.7 for installing one package which leverages fortran codes. Since then my conda started to functioning weirdly. 

Although one of my friend from Caltech told me not to use pws because of its distortion of waveform, many papers I read about DAS ambient noise imaging use tf-pws for enhancing SNR. 

I will try different stacking methods for my field data. Thank you Prof. Yang!
